### ISSUE TITLE
Change Scene draw API

### ISSUE THREAD

**Issue by imbrn** [imbrn/ace#17]
Instead of using `this.canvas` inside a Scene implementation of `draw` method, it's more appropriate and favors encapsulation to use `canvas` as an argument of that.

We can see an example in the `moving-ball` example:

https://github.com/imbrn/ace/blob/235947c4013c2bf8ae5003d62b4cc60c6f3ba881/examples/moving-ball/index.ts#L35-L41

After this API change it should look like:

```js
draw(canvas: Canvas): void { 
   canvas.fillStyle = "black"; 
   canvas.fill(rect({ x: 0, y: 0, width: this.resolution.width, height: this.resolution.height })); 
    
   canvas.fillStyle = "green"; 
   canvas.fill(circle({ x: this.x, y: this.y, radius: 50 })); 
 }
```

In this way, we can avoid exposing canvas abstraction to the whole scene but just for the drawing step.

**Comment by maxwelfcoelho** [comment]
Can I try it? thank you!
